### ISSUE TITLE
Bare Minimum Setup - help

### ISSUE THREAD

**Issue by jtone2k8** [iosifache/ctfd-solve-webhook-plugin#1]
Love the idea of the first blood announcements going into Mattermost!

Just having some issues getting it up and running on a new vm though.

start off running this command: git clone --recursive https://github.com/iosifache/ctfd-solve-webhook-plugin

to pull down this repo and the latest CTFd (3.6.0)

Here is where i got a little lost, SOLVE_WEBHOOK_URL=, Is this the url of the mattermost webhook container? or Should this be where i want traffic to be sent to?

I had this running on a couple of test servers and the mattermost webhook container ran on one instance with an existing CTFd stack running, but i used the same base snapshot and ran the recursive clone and i am unable to get the mattermost webhook to run past 2/3 second mark. without any logs... its tough to track down the issue.

Next up on the instance with the webhook python server running.... i am able to post messages to the mattermost server where i want it to go, but i cannot seem to be able to get any of the challenge solves to go to the channels.

Do you have any thoughts or tricks that i might be missing?

**Comment by iosifache** [comment]
Hey @jtone2k8 👋,

> Here is where i got a little lost, SOLVE_WEBHOOK_URL=, Is this the url of the mattermost webhook container? or Should this be where i want traffic to be sent to?

`SOLVE_WEBHOOK_URL` is the URL of the webhook. In your case, yes, this is the URL where [the Mattermost webhook script](https://github.com/iosifache/ctfd-solve-webhook-plugin/blob/main/webhooks/mattermost/server.py) runs (i.e. the one exposed by the [Mattermost webhook container](https://github.com/iosifache/ctfd-solve-webhook-plugin/blob/main/webhooks/mattermost/Dockerfile)).

> i am unable to get the mattermost webhook to run past 2/3 second mark

What mark are you referring to?

In addition, did you set up the Mattermost webhook environment variables as highlighted by the [`README.md`](https://github.com/iosifache/ctfd-solve-webhook-plugin#available-aspects)?

https://github.com/iosifache/ctfd-solve-webhook-plugin/blob/01ce01919c9db531143598de0a43e11fad280fa5/webhooks/mattermost/Dockerfile#L5-L11

You can also test the Mattermost webhook separately, via this command:

```bash
curl http://<mattermost_webhook_ip> -d '{"challenge": "exploit_me", "category": "pwn", "team": "LiveOverflow", "user": "", "solve_id": 1}' -H "Content-Type: application/json"
```

You can use a similar command to test the Mattermost instance. Please mention if you plan to use [a Mattermost bot](https://developers.mattermost.com/integrate/reference/bot-accounts/) or [an incoming webhook](https://developers.mattermost.com/integrate/webhooks/incoming/).

> without any logs... its tough to track down the issue.

Let's first try to solve the issue with your deployment. We can then start to think about what should be done to make the lives easier for new users (for example, adding more documentation or improving the logging) 🤝.

**Comment by jtone2k8** [comment]
I think the issue with the web server container stopping was due to the ENV variables not set properly. I think my docker-compose with blank variables was overwriting my Dockerfile variables? I think the variables need to be matching... or only in one place or the other, as long as the blank variables are not in the compose file.

**edit** One thing i did not consider is that changes to the Dockerfile did not take effect unless the image was destroyed and rebuilt, so the variables need to be in the Dockerfile also.

If i removed the empty environment section  the compose file and had variables in the Dockerfile... it worked; if the docker compose file had the env section with empty variables, the container broke even if the variables were defined in the Dockerfile.

I have configured a Mattermost Bot, and used this command to post to the "announcements" channel:

`curl -i -X POST -H 'Content-Type: application/json' -d '{"channel_id":"<channel id>", "message":"This is a message from a bot", "props":{"attachments": [{"pretext": "Look some text","text": "This is text"}]}}' -H 'Authorization: Bearer <auth token>' https://<ip/dns>/api/v4/posts`

channel_id was the actual id and not the name of the channel plus the bot auth token

Testing the mattermost webhook with this curl command:

`curl http://<ip>:8002 -d '{"challenge": "exploit_me", "category": "pwn", "team": "LiveOverflow", "user": "", "solve_id": 1}' -H "Content-Type: application/json"`

No response from the server; which was good.

Log from the server gave me this:

`ctfd-solve-webhook-plugin-mattermost-1  | <IP> - - [29/Nov/2023 20:49:49] "POST / HTTP/1.1" 401 -`

Here is the compose file for the stack:
```
version: '2'

services:
  ctfd:
    image: ctfd/ctfd
    user: root
    restart: always
    networks:
      default:
      internal:
    ports:
      - "8001:8000"
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - ./CTFd:/opt/CTFd
      - ./solve-webhook-plugin:/opt/CTFd/CTFd/plugins/solve-webhook-plugin
    environment:
      - SECRET_KEY=test_infra_dont_bother
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - SOLVE_WEBHOOK_URL=http://127.0.0.1:8002
      - SOLVE_WEBHOOK_LIMIT=3
    depends_on:
      - db
    profiles:
      - ctfd

  db:
    image: mariadb:10.4.12
    restart: always
    networks:
      internal:
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
    profiles:
      - ctfd

  cache:
    image: redis:4
    restart: always
    networks:
        internal:
    volumes:
    - .data/redis:/data
    profiles:
      - ctfd

  mattermost:
    image: mattermost_webhook
    build: webhooks/mattermost
    environment:
      - MATTERMOST_WEBHOOK_IS_BOT=1
      - MATTERMOST_WEBHOOK_BOT_TOKEN=<bot token>
      - MATTERMOST_WEBHOOK_URL=https://<ip/dns>/api/v4/posts
      - MATTERMOST_WEBHOOK_CHANNEL=<channel id>
      - MATTERMOST_WEBHOOK_USERNAME=
      - MATTERMOST_WEBHOOK_ICON_EMOJI=trumpet
      - MATTERMOST_WEBHOOK_AUTH_TOKEN=

    networks:
      default:
      internal:
    ports:
      - "8002:8080"
    profiles:
      - mattermost

networks:
  default:
  internal:
      internal: true
```

With this Compose ran with both CTFd and mattermost profiles i have a 401 error from the mattermost webhook server.
